### ISSUE TITLE
History function not responding

### ISSUE THREAD

**Issue by Tyrim** [teroparvinen/foundry-xp-tally#3]
Hey there! Sweet mod, but the history button doesn't seem to be working. Here's what the console has to say about it:
`TypeError: An error occurred while rendering History 98. uuid.startsWith is not a function
    at Object.parseUuid (commons.js:2894:15)
    at fromUuidSync (foundry.js:4818:77)
    at history.js:43:49
    at Array.map (<anonymous>)
    at history.js:43:40
    at Array.map (<anonymous>)
    at history.js:39:46
    at Array.map (<anonymous>)
    at History.getData (history.js:37:39)
    at History._render (foundry.js:5736:29)
    at History._render (foundry.js:6456:17)
    at History.render (foundry.js:5693:10)
    at History.activate (history.js:12:27)
    at Object.onclick (tracker.js:132:29)
    at HTMLAnchorElement.<anonymous> (foundry.js:5865:16)
    at HTMLAnchorElement.dispatch (jquery.min.js:2:43184)
    at y.handle (jquery.min.js:2:41168)`

**Comment by teroparvinen** [comment]
Thanks for the report! This should now be fixed.
